name: "CANBus"
description: "comfort CanBus integration of your Fiat Ducato based campervan into Home Assistant"
version: "0.0.2"
slug: "canbus"
init: false
startup: services
boot: auto

arch:
  - amd64
  - aarch64
  - armv7
  - armhf

privileged:
  - NET_ADMIN
  - NET_RAW

devices:
  - /dev/net/tun

host_network: true

options:
  MQTTBroker: "core-mosquitto"
  MQTTUser: ""
  MQTTPassword: ""

schema:
  MQTTBroker: str
  MQTTUser: str?
  MQTTPassword: password?